/* Auto-generated by genmsg_cpp for file /homes/awalsman/ros/local/pr-ros-pkg/trunk/perception_utils/apriltags/srv/Start.srv */
#ifndef APRILTAGS_SERVICE_START_H
#define APRILTAGS_SERVICE_START_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace apriltags
{
template <class ContainerAllocator>
struct StartRequest_ {
  typedef StartRequest_<ContainerAllocator> Type;

  StartRequest_()
  {
  }

  StartRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::apriltags::StartRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apriltags::StartRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StartRequest
typedef  ::apriltags::StartRequest_<std::allocator<void> > StartRequest;

typedef boost::shared_ptr< ::apriltags::StartRequest> StartRequestPtr;
typedef boost::shared_ptr< ::apriltags::StartRequest const> StartRequestConstPtr;


template <class ContainerAllocator>
struct StartResponse_ {
  typedef StartResponse_<ContainerAllocator> Type;

  StartResponse_()
  : id(0)
  {
  }

  StartResponse_(const ContainerAllocator& _alloc)
  : id(0)
  {
  }

  typedef int32_t _id_type;
  int32_t id;


  typedef boost::shared_ptr< ::apriltags::StartResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apriltags::StartResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StartResponse
typedef  ::apriltags::StartResponse_<std::allocator<void> > StartResponse;

typedef boost::shared_ptr< ::apriltags::StartResponse> StartResponsePtr;
typedef boost::shared_ptr< ::apriltags::StartResponse const> StartResponseConstPtr;

struct Start
{

typedef StartRequest Request;
typedef StartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Start
} // namespace apriltags

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::apriltags::StartRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::apriltags::StartRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::apriltags::StartRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::apriltags::StartRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::apriltags::StartRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "apriltags/StartRequest";
  }

  static const char* value(const  ::apriltags::StartRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::apriltags::StartRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::apriltags::StartRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::apriltags::StartRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::apriltags::StartResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::apriltags::StartResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::apriltags::StartResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c5e4a7d59c68f74eabcec876a00216aa";
  }

  static const char* value(const  ::apriltags::StartResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc5e4a7d59c68f74eULL;
  static const uint64_t static_value2 = 0xabcec876a00216aaULL;
};

template<class ContainerAllocator>
struct DataType< ::apriltags::StartResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "apriltags/StartResponse";
  }

  static const char* value(const  ::apriltags::StartResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::apriltags::StartResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 id\n\
\n\
\n\
";
  }

  static const char* value(const  ::apriltags::StartResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::apriltags::StartResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::apriltags::StartRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StartRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::apriltags::StartResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.id);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StartResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<apriltags::Start> {
  static const char* value() 
  {
    return "c5e4a7d59c68f74eabcec876a00216aa";
  }

  static const char* value(const apriltags::Start&) { return value(); } 
};

template<>
struct DataType<apriltags::Start> {
  static const char* value() 
  {
    return "apriltags/Start";
  }

  static const char* value(const apriltags::Start&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<apriltags::StartRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c5e4a7d59c68f74eabcec876a00216aa";
  }

  static const char* value(const apriltags::StartRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<apriltags::StartRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "apriltags/Start";
  }

  static const char* value(const apriltags::StartRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<apriltags::StartResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c5e4a7d59c68f74eabcec876a00216aa";
  }

  static const char* value(const apriltags::StartResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<apriltags::StartResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "apriltags/Start";
  }

  static const char* value(const apriltags::StartResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // APRILTAGS_SERVICE_START_H

