/* Auto-generated by genmsg_cpp for file /homes/awalsman/ros/local/pr-ros-pkg/trunk/perception_utils/apriltags/srv/Stop.srv */
#ifndef APRILTAGS_SERVICE_STOP_H
#define APRILTAGS_SERVICE_STOP_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace apriltags
{
template <class ContainerAllocator>
struct StopRequest_ {
  typedef StopRequest_<ContainerAllocator> Type;

  StopRequest_()
  : id(0)
  {
  }

  StopRequest_(const ContainerAllocator& _alloc)
  : id(0)
  {
  }

  typedef int32_t _id_type;
  int32_t id;


  typedef boost::shared_ptr< ::apriltags::StopRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apriltags::StopRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StopRequest
typedef  ::apriltags::StopRequest_<std::allocator<void> > StopRequest;

typedef boost::shared_ptr< ::apriltags::StopRequest> StopRequestPtr;
typedef boost::shared_ptr< ::apriltags::StopRequest const> StopRequestConstPtr;


template <class ContainerAllocator>
struct StopResponse_ {
  typedef StopResponse_<ContainerAllocator> Type;

  StopResponse_()
  : closed(false)
  {
  }

  StopResponse_(const ContainerAllocator& _alloc)
  : closed(false)
  {
  }

  typedef uint8_t _closed_type;
  uint8_t closed;


  typedef boost::shared_ptr< ::apriltags::StopResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apriltags::StopResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StopResponse
typedef  ::apriltags::StopResponse_<std::allocator<void> > StopResponse;

typedef boost::shared_ptr< ::apriltags::StopResponse> StopResponsePtr;
typedef boost::shared_ptr< ::apriltags::StopResponse const> StopResponseConstPtr;

struct Stop
{

typedef StopRequest Request;
typedef StopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Stop
} // namespace apriltags

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::apriltags::StopRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::apriltags::StopRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::apriltags::StopRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c5e4a7d59c68f74eabcec876a00216aa";
  }

  static const char* value(const  ::apriltags::StopRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc5e4a7d59c68f74eULL;
  static const uint64_t static_value2 = 0xabcec876a00216aaULL;
};

template<class ContainerAllocator>
struct DataType< ::apriltags::StopRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "apriltags/StopRequest";
  }

  static const char* value(const  ::apriltags::StopRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::apriltags::StopRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 id\n\
\n\
";
  }

  static const char* value(const  ::apriltags::StopRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::apriltags::StopRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::apriltags::StopResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::apriltags::StopResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::apriltags::StopResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2bbf27bc7e22a99989ad02833686f52e";
  }

  static const char* value(const  ::apriltags::StopResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2bbf27bc7e22a999ULL;
  static const uint64_t static_value2 = 0x89ad02833686f52eULL;
};

template<class ContainerAllocator>
struct DataType< ::apriltags::StopResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "apriltags/StopResponse";
  }

  static const char* value(const  ::apriltags::StopResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::apriltags::StopResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool closed\n\
\n\
\n\
";
  }

  static const char* value(const  ::apriltags::StopResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::apriltags::StopResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::apriltags::StopRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.id);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StopRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::apriltags::StopResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.closed);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StopResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<apriltags::Stop> {
  static const char* value() 
  {
    return "5a2f95a571a8333029c467ad17835c18";
  }

  static const char* value(const apriltags::Stop&) { return value(); } 
};

template<>
struct DataType<apriltags::Stop> {
  static const char* value() 
  {
    return "apriltags/Stop";
  }

  static const char* value(const apriltags::Stop&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<apriltags::StopRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5a2f95a571a8333029c467ad17835c18";
  }

  static const char* value(const apriltags::StopRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<apriltags::StopRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "apriltags/Stop";
  }

  static const char* value(const apriltags::StopRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<apriltags::StopResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5a2f95a571a8333029c467ad17835c18";
  }

  static const char* value(const apriltags::StopResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<apriltags::StopResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "apriltags/Stop";
  }

  static const char* value(const apriltags::StopResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // APRILTAGS_SERVICE_STOP_H

