/* Auto-generated by genmsg_cpp for file /homes/awalsman/ros/local/pr-ros-pkg/trunk/perception_utils/apriltags/srv/StopAll.srv */
#ifndef APRILTAGS_SERVICE_STOPALL_H
#define APRILTAGS_SERVICE_STOPALL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace apriltags
{
template <class ContainerAllocator>
struct StopAllRequest_ {
  typedef StopAllRequest_<ContainerAllocator> Type;

  StopAllRequest_()
  {
  }

  StopAllRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::apriltags::StopAllRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apriltags::StopAllRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StopAllRequest
typedef  ::apriltags::StopAllRequest_<std::allocator<void> > StopAllRequest;

typedef boost::shared_ptr< ::apriltags::StopAllRequest> StopAllRequestPtr;
typedef boost::shared_ptr< ::apriltags::StopAllRequest const> StopAllRequestConstPtr;


template <class ContainerAllocator>
struct StopAllResponse_ {
  typedef StopAllResponse_<ContainerAllocator> Type;

  StopAllResponse_()
  {
  }

  StopAllResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::apriltags::StopAllResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apriltags::StopAllResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StopAllResponse
typedef  ::apriltags::StopAllResponse_<std::allocator<void> > StopAllResponse;

typedef boost::shared_ptr< ::apriltags::StopAllResponse> StopAllResponsePtr;
typedef boost::shared_ptr< ::apriltags::StopAllResponse const> StopAllResponseConstPtr;

struct StopAll
{

typedef StopAllRequest Request;
typedef StopAllResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct StopAll
} // namespace apriltags

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::apriltags::StopAllRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::apriltags::StopAllRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::apriltags::StopAllRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::apriltags::StopAllRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::apriltags::StopAllRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "apriltags/StopAllRequest";
  }

  static const char* value(const  ::apriltags::StopAllRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::apriltags::StopAllRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::apriltags::StopAllRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::apriltags::StopAllRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::apriltags::StopAllResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::apriltags::StopAllResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::apriltags::StopAllResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::apriltags::StopAllResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::apriltags::StopAllResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "apriltags/StopAllResponse";
  }

  static const char* value(const  ::apriltags::StopAllResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::apriltags::StopAllResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::apriltags::StopAllResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::apriltags::StopAllResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::apriltags::StopAllRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StopAllRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::apriltags::StopAllResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StopAllResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<apriltags::StopAll> {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const apriltags::StopAll&) { return value(); } 
};

template<>
struct DataType<apriltags::StopAll> {
  static const char* value() 
  {
    return "apriltags/StopAll";
  }

  static const char* value(const apriltags::StopAll&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<apriltags::StopAllRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const apriltags::StopAllRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<apriltags::StopAllRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "apriltags/StopAll";
  }

  static const char* value(const apriltags::StopAllRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<apriltags::StopAllResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const apriltags::StopAllResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<apriltags::StopAllResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "apriltags/StopAll";
  }

  static const char* value(const apriltags::StopAllResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // APRILTAGS_SERVICE_STOPALL_H

